# Generated by Django 4.2.9 on 2024-04-24 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_city_filial_organisation_organisationtype_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filial',
            options={'ordering': ['organisation'], 'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
        migrations.RenameField(
            model_name='city',
            old_name='region_id',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='filial',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='filial',
            old_name='organisation_id',
            new_name='organisation',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='organisation_type_id',
            new_name='organisation_type',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='filial_id',
            new_name='filial',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_type_id',
            new_name='product_type',
        ),
        migrations.RenameField(
            model_name='producttype',
            old_name='organisation_type_id',
            new_name='organisation_type',
        ),
        migrations.RenameField(
            model_name='producttype',
            old_name='product_class_id',
            new_name='product_class',
        ),
    ]
