# Generated by Django 4.2.9 on 2024-06-20 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_city_name_lowr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="name_lowr",
        ),
    ]
